/* Fisio+ — aplicação local/offline */
(() => {
'use strict';
const DB_NAME='FisioMaisDB', DB_VERSION=2;
let db,currentUser=null,deferredInstallPrompt=null,editingPatientId=null;
const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll('.screen')];
const normalize=text=>String(text??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=text=>String(text??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const now=()=>new Date().toISOString();
function showScreen(id){screens.forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;
 if(!d.objectStoreNames.contains('users'))d.createObjectStore('users',{keyPath:'username'});
 if(!d.objectStoreNames.contains('patients')){const s=d.createObjectStore('patients',{keyPath:'id',autoIncrement:true});s.createIndex('username','username',{unique:false});}
 else if(!d.transaction.objectStore('patients').indexNames.contains('username'))d.transaction.objectStore('patients').createIndex('username','username',{unique:false});
 if(!d.objectStoreNames.contains('searchHistory')){const s=d.createObjectStore('searchHistory',{keyPath:'id',autoIncrement:true});s.createIndex('username','username',{unique:false});}
};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)});}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function reqPromise(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
const get=(s,k)=>reqPromise(store(s).get(k));const put=(s,v)=>reqPromise(store(s,'readwrite').put(v));const add=(s,v)=>reqPromise(store(s,'readwrite').add(v));const del=(s,k)=>reqPromise(store(s,'readwrite').delete(k));
function allByUser(s,user){return reqPromise(store(s).index('username').getAll(user))}
function theme(){document.documentElement.classList.toggle('dark');localStorage.setItem('fisioTheme',document.documentElement.classList.contains('dark')?'dark':'light')}
function loadTheme(){const t=localStorage.getItem('fisioTheme');if(t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches))document.documentElement.classList.add('dark')}
function cleanUsername(v){let x=String(v).replace(/\s+/g,'').replace(/^@+/,'').replace(/[^a-zA-Z0-9._-]/g,'').slice(0,39);return x?'@'+x:''}
async function enterUser(){const input=$('username'),clean=cleanUsername(input.value);input.value=clean;if(clean.length<2){$('user-feedback').textContent='Digite um usuário, por exemplo @malu.';return}let user=await get('users',clean);if(!user){user={username:clean,createdAt:now(),lastLogin:now()};await put('users',user);$('user-feedback').textContent='Novo usuário criado neste dispositivo.'}else{user.lastLogin=now();await put('users',user);$('user-feedback').textContent='Usuário encontrado. Login local realizado.'}currentUser=clean;localStorage.setItem('fisioCurrentUser',clean);$('current-user').textContent=clean;showScreen('main-screen');await renderRecentSearches()}
async function restoreUser(){const u=localStorage.getItem('fisioCurrentUser');if(u&&await get('users',u)){currentUser=u;$('current-user').textContent=u;showScreen('main-screen')}}
function searchableText(item){return [item.nome_patologia,item.regiao_corpo,...(item.palavras_chave||[]),...(item.sintomas||[])].join(' ')}
function searchDatabase(term){const q=normalize(term);if(!q)return SCIENTIFIC_DATABASE;return SCIENTIFIC_DATABASE.filter(item=>normalize(searchableText(item)).includes(q))}
async function saveSearch(term){const q=String(term).trim();if(!currentUser||!q)return;const old=await allByUser('searchHistory',currentUser);const duplicate=old.find(x=>normalize(x.term)===normalize(q));if(duplicate)await del('searchHistory',duplicate.id);await add('searchHistory',{username:currentUser,term:q,createdAt:now()});const all=await allByUser('searchHistory',currentUser);all.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));for(const x of all.slice(12))await del('searchHistory',x.id);await renderRecentSearches()}
async function renderRecentSearches(){const box=$('recent-searches');if(!box||!currentUser)return;const all=(await allByUser('searchHistory',currentUser)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8);box.innerHTML=all.length?`<div class="recent-title">Pesquisas Recentes</div><div class="recent-list">${all.map(x=>`<button class="recent-search" data-recent-search="${esc(x.term)}">${esc(x.term)}</button>`).join('')}</div>`:'<div class="tiny-note">Pesquisas recentes aparecerão aqui.</div>'}
function renderDatabase(term=''){const r=searchDatabase(term);$('db-count').textContent=`${r.length} ${r.length===1?'item':'itens'}`;$('database-results').innerHTML=r.length?r.map(item=>`<article class="db-card"><h3>${esc(item.nome_patologia)}</h3><span class="tag">${esc(item.regiao_corpo)}</span>${(item.palavras_chave||[]).slice(0,6).map(k=>`<span class="tag">${esc(k)}</span>`).join('')}<h4>Testes ortopédicos / neurológicos</h4><ul>${item.testes_ortopedicos_neurologicos.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Conduta terapêutica</h4><ul>${item.conduta_terapeutica.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Exercícios específicos</h4>${item.exercicios_especificos.map(x=>`<div class="exercise"><strong>${esc(x.nome)}</strong>${esc(x.descricao)}</div>`).join('')}<h4>Referências científicas</h4><div class="ref">${item.referencias_cientificas.map(x=>`• ${esc(x)}`).join('<br>')}</div></article>`).join(''):'<div class="empty">Nenhum registro encontrado. Tente outro termo; acentos não são obrigatórios.</div>'}
function pathologySuggestions(term=''){const q=normalize(term);const r=(q?SCIENTIFIC_DATABASE.filter(item=>normalize(searchableText(item)).includes(q)):[]).slice(0,8);$('pathology-suggestions').innerHTML=r.map(x=>`<div class="suggestion" data-path-index="${SCIENTIFIC_DATABASE.indexOf(x)}"><strong>${esc(x.nome_patologia)}</strong> — ${esc(x.regiao_corpo)}</div>`).join('')}
function selectedChecks(id){return [...document.querySelectorAll(`#${id} input:checked`)].map(x=>x.value)}
function buildAdaptations(patient){const risks=patient.risks.map(normalize),syms=patient.symptoms.map(normalize),out=[];
 if(patient.age>=65)out.push('Idade ≥65 anos: considerar menor impacto, progressão gradual, pausas adequadas e maior ênfase em segurança funcional e risco de queda.');
 if(risks.includes('obesidade')||risks.includes('obesidade sarcopenica'))out.push('Obesidade/obesidade sarcopênica: priorizar estratégias de baixo impacto e superfícies/apoios que facilitem transferências e reduzam sobrecarga desnecessária.');
 if(risks.includes('hipertensao'))out.push('Hipertensão: monitorar resposta cardiovascular conforme contexto; evitar manobra de Valsalva e esforço sustentado excessivo.');
 if(risks.includes('diabetes'))out.push('Diabetes: considerar inspeção dos pés, sensibilidade, risco cutâneo e resposta ao exercício; ajustar conforme controle metabólico e orientação da equipe.');
 if(risks.includes('osteoporose'))out.push('Osteoporose: priorizar progressão segura de força e controle, evitando impactos ou alavancas/posições inadequadas ao risco individual de fratura.');
 if(risks.includes('doenca cardiovascular'))out.push('Doença cardiovascular: considerar intensidade, sintomas e parâmetros clínicos; interromper diante de sinais de intolerância e seguir protocolo assistencial.');
 if(risks.includes('risco de queda')||risks.includes('historico de queda'))out.push('Risco/histórico de queda: realizar tarefas em ambiente seguro, com apoio próximo e progressão do desafio somente após domínio da tarefa.');
 if(risks.includes('sedentarismo'))out.push('Sedentarismo: iniciar com volume tolerável e progressão gradual da exposição à atividade física.');
 if(risks.includes('tabagismo'))out.push('Tabagismo: considerar capacidade cardiorrespiratória e tolerância ao esforço; orientar avaliação/cessação dentro da equipe de saúde quando pertinente.');
 if(risks.includes('fibromialgia'))out.push('Fibromialgia: priorizar pacing, progressão lenta, recuperação e resposta individual, evitando aumentos bruscos de volume.');
 if(syms.includes('fadiga muscular'))out.push('Fadiga muscular: distribuir volume, usar intervalos de recuperação e monitorar resposta tardia.');
 if(syms.includes('desequilibrio'))out.push('Desequilíbrio: reduzir risco ambiental e usar apoio/supervisão durante tarefas posturais.');
 if(syms.includes('alteracao de sensibilidade (parestesia)'))out.push('Alteração de sensibilidade: monitorar resposta neurológica e integridade cutânea; piora persistente requer reavaliação.');
 if(syms.includes('dor neuropatica'))out.push('Dor neuropática: acompanhar distribuição, intensidade e fatores de agravamento; evitar assumir que toda dor é exclusivamente musculoesquelética.');
 if(syms.includes('falta de ar'))out.push('Falta de ar: não assumir origem musculoesquelética; monitorar sinais/sintomas e considerar avaliação clínica antes de progressões de esforço.');
 if(syms.includes('edema'))out.push('Edema: monitorar evolução, resposta à carga e sinais associados; investigar quando desproporcional ou de início atípico.');
 if(syms.includes('dor irradiada'))out.push('Dor irradiada: acompanhar distribuição e alterações neurológicas; déficits progressivos ou sinais de alerta exigem avaliação apropriada.');
 if(!out.length)out.push('Nenhum modificador automático adicional foi identificado; a aplicação dos exercícios deve ser individualizada após avaliação profissional.');return out}
async function savePatient(e){e.preventDefault();const idx=Number($('selected-pathology').value),path=SCIENTIFIC_DATABASE[idx];if(!path)return alert('Selecione uma patologia da Base Científica.');const existing=editingPatientId?await get('patients',editingPatientId):null;const patient={id:editingPatientId||undefined,username:currentUser,name:$('patient-name').value.trim(),age:Number($('patient-age').value),risks:selectedChecks('risk-checks'),symptoms:selectedChecks('symptom-checks'),pathologyIndex:idx,pathologyName:path.nome_patologia,notes:$('patient-notes').value.trim(),createdAt:existing?.createdAt||now(),updatedAt:now()};if(!patient.name||!Number.isFinite(patient.age))return alert('Preencha nome e idade.');patient.id=editingPatientId?await put('patients',patient):await add('patients',patient);renderPatientResult(patient,path);showScreen('patient-result-screen')}
async function renderPatients(term=''){const all=(await allByUser('patients',currentUser)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const q=normalize(term),list=all.filter(p=>!q||normalize(p.name).includes(q));$('patients-list').innerHTML=list.length?list.map(p=>`<article class="patient-card" data-patient-id="${p.id}"><h3>${esc(p.name)}</h3><p>${p.age} anos • ${esc(p.pathologyName)}</p><span class="tag">${esc(p.risks.length?p.risks.join(', '):'Sem fatores informados')}</span></article>`).join(''):'<div class="empty">Nenhum paciente encontrado.</div>'}
function renderPatientResult(p,path){const adaptations=buildAdaptations(p);$('result-title').textContent=p.name;$('patient-summary').innerHTML=`<article class="result-card"><h3>Perfil</h3><p><strong>${esc(p.name)}</strong></p><p>${p.age} anos</p><p>Fatores: ${esc(p.risks.join(', ')||'não informados')}</p></article><article class="result-card"><h3>Queixa principal</h3><p><strong>${esc(path.nome_patologia)}</strong></p><p>${esc(path.regiao_corpo)}</p><p>Sintomas: ${esc(p.symptoms.join(', ')||'não informados')}</p></article><article class="result-card full"><h3>Exercícios específicos da patologia</h3>${path.exercicios_especificos.map(x=>`<div class="exercise"><strong>${esc(x.nome)}</strong>${esc(x.descricao)}</div>`).join('')}<div class="adaptation"><strong>Adaptações pelo Perfil</strong><ul>${adaptations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></article><article class="result-card full"><h3>Conduta terapêutica na Base</h3><ul>${path.conduta_terapeutica.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Observações clínicas</h4><p>${esc(p.notes||'Nenhuma observação registrada.')}</p></article><article class="result-card full"><h3>Referências científicas</h3><div class="ref">${path.referencias_cientificas.map(x=>`• ${esc(x)}`).join('<br>')}</div></article><article class="result-card full"><button class="btn btn-yellow" id="edit-current">✎ Editar paciente</button> <button class="btn" id="delete-current">Excluir paciente</button></article>`;$('edit-current').onclick=()=>openPatientForm(p);$('delete-current').onclick=async()=>{if(confirm('Excluir permanentemente este paciente deste dispositivo?')){await del('patients',p.id);showScreen('patients-screen');renderPatients($('patient-search').value)}}}
function resetPatientForm(){$('patient-form').reset();$('selected-pathology').value='';$('pathology-search').value='';$('pathology-suggestions').innerHTML='';editingPatientId=null;$('patient-form-title').textContent='Novo paciente'}
function openPatientForm(p=null){resetPatientForm();if(p){editingPatientId=p.id;$('patient-form-title').textContent='Editar paciente';$('patient-name').value=p.name;$('patient-age').value=p.age;$('patient-notes').value=p.notes||'';$('selected-pathology').value=p.pathologyIndex;$('pathology-search').value=SCIENTIFIC_DATABASE[p.pathologyIndex]?.nome_patologia||'';document.querySelectorAll('#risk-checks input').forEach(i=>i.checked=p.risks.includes(i.value));document.querySelectorAll('#symptom-checks input').forEach(i=>i.checked=p.symptoms.includes(i.value))}showScreen('patient-form-screen')}
async function logout(){currentUser=null;localStorage.removeItem('fisioCurrentUser');$('username').value='';showScreen('welcome-screen')}
function install(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null})}else alert('O prompt nativo não está disponível agora. No Chrome/Edge, use o menu do navegador → Instalar aplicativo. No iPhone/iPad, use Compartilhar → Adicionar à Tela de Início.')}
document.addEventListener('click',async e=>{const themeBtn=e.target.closest('[data-action="theme"]');if(themeBtn)theme();const back=e.target.closest('[data-back]');if(back){showScreen(back.dataset.back==='main'?'main-screen':'patients-screen');if(back.dataset.back==='patients')await renderPatients($('patient-search').value)}const sug=e.target.closest('[data-path-index]');if(sug){const i=Number(sug.dataset.pathIndex);$('selected-pathology').value=i;$('pathology-search').value=SCIENTIFIC_DATABASE[i].nome_patologia;$('pathology-suggestions').innerHTML=''}const recent=e.target.closest('[data-recent-search]');if(recent){const term=recent.dataset.recentSearch;$('database-search').value=term;renderDatabase(term);await saveSearch(term)}const card=e.target.closest('[data-patient-id]');if(card){const p=await get('patients',Number(card.dataset.patientId));if(p){renderPatientResult(p,SCIENTIFIC_DATABASE[p.pathologyIndex]);showScreen('patient-result-screen')}}});
$('start-btn').onclick=()=>showScreen('user-screen');$('enter-btn').onclick=enterUser;$('username').addEventListener('input',e=>e.target.value=e.target.value.replace(/\s/g,''));$('username').addEventListener('keydown',e=>{if(e.key==='Enter')enterUser()});$('open-database').onclick=async()=>{showScreen('database-screen');renderDatabase();await renderRecentSearches()};$('open-patients').onclick=async()=>{showScreen('patients-screen');await renderPatients()};$('database-search').addEventListener('input',e=>renderDatabase(e.target.value));$('database-search').addEventListener('change',e=>saveSearch(e.target.value));$('database-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveSearch(e.target.value)}});$('patient-search').addEventListener('input',e=>renderPatients(e.target.value));$('new-patient-btn').onclick=()=>openPatientForm();$('back-to-patients').onclick=async()=>{showScreen('patients-screen');await renderPatients($('patient-search').value)};$('cancel-patient').onclick=async()=>{showScreen('patients-screen');await renderPatients($('patient-search').value)};$('patient-form').addEventListener('submit',savePatient);$('pathology-search').addEventListener('input',e=>{$('selected-pathology').value='';pathologySuggestions(e.target.value)});$('logout-btn').onclick=logout;$('install-btn').onclick=install;$('install-banner-btn').onclick=install;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('install-btn').hidden=false;$('install-banner').hidden=false});window.addEventListener('appinstalled',()=>{$('install-banner').hidden=true;$('install-btn').hidden=true;deferredInstallPrompt=null});
async function init(){loadTheme();await openDB();$('install-btn').hidden=false;await restoreUser();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(console.error)}
init().catch(err=>{console.error(err);alert('Não foi possível iniciar o armazenamento local. Publique no GitHub Pages ou execute em um servidor local; não abra diretamente como file://.')});
})();
